// registry — 工具清单（唯一数据源）
// 加工具 = 在 TOOLS 里加一条；不需要改主页 HTML。
// 一个工具可同时属于多个类别与多个场景，主页据此自由重组。

// ---------- 类别：按“它是什么” ----------
const CATEGORIES = [
  { id: "text",    name: "文字处理", desc: "改写、转换、清理、比对文字" },
  { id: "measure", name: "计量核查", desc: "统计换算、样本量、信度" },
  { id: "encode",  name: "编码转换", desc: "格式与编码之间的互转" },
  { id: "media",   name: "图像音视", desc: "图片与多媒体素材处理" },
  { id: "litdata", name: "文献与数据", desc: "文献管理、数据清洗与编码" },
];

// ---------- 场景：按“什么时候用” ----------
// steps 是有顺序的工作流，主页会按顺序展示成流程条。
const SCENARIOS = [
  {
    id: "cross-strait",
    name: "发两岸三地稿",
    desc: "先换字形和台港用词，再核字数与口播时长。",
    steps: ["s2t", "textstats"],
  },
  {
    id: "filing",
    name: "交稿前",
    desc: "先扫地，改稿对照，再看字数与口播时长。",
    steps: ["tidy", "diffmark", "textstats"],
  },
  {
    id: "send-photo",
    name: "供图",
    desc: "原图压到能当附件，EXIF 去掉。",
    steps: ["imgshrink"],
  },
  {
    id: "foreign-desk",
    name: "处理外媒",
    desc: "发稿时间换成北京时间，还原乱码，繁体转回简体。",
    steps: ["timezone", "codec", "s2t"],
  },
  {
    id: "verify",
    name: "核材料",
    desc: "哈希核对有没有被改，解开转义链接和 token。",
    steps: ["codec"],
  },
  {
    id: "paper-writing",
    name: "写论文",
    desc: "PDF 抽元数据，修好导出的参考文献，转成要投的格式，统计量出 APA 报告。",
    steps: ["scipdf", "bibfix", "citecheck", "pvalue"],
  },
  {
    id: "interview",
    name: "访谈脱敏",
    desc: "人名机构证件号遮掉，逐处复核，导出伦理审查要的映射表。",
    steps: ["redact"],
  },
  {
    id: "wash-data",
    name: "洗问卷数据",
    desc: "编码、分隔符、重复行、空列——导出的 CSV 先过一遍再进 SPSS / R。",
    steps: ["csvclean"],
  },
];

// ---------- 工具 ----------
// status: live | wip | planned
const TOOLS = [
  {
    id: "codec",
    name: "codec",
    title: "编解码",
    tagline: "还原乱码、解开转义、核对文件哈希",
    desc: "还原邮件里的乱码附件名、解开被转义的链接、算素材文件的哈希核对是否被改动。",
    url: "https://icgma.github.io/codec/",
    repo: "https://github.com/icgma/codec",
    external: true,
    status: "live",
    categories: ["encode", "text"],
    scenarios: ["foreign-desk", "verify"],
    tags: ["Base64", "URL 编码", "Hex", "JWT", "SHA"],
    keywords: ["编码", "解码", "加密", "解密", "乱码", "转义", "哈希", "md5", "校验", "base64", "token"],
    icon: '<path fill="currentColor" d="M9.4 16.6 4.8 12l4.6-4.6L8 6l-6 6 6 6 1.4-1.4Zm5.2 0L19.2 12l-4.6-4.6L16 6l6 6-6 6-1.4-1.4Z"/>',
  },
  {
    id: "s2t",
    name: "s2t",
    title: "简繁转换",
    tagline: "简繁转换，台港用词一并改，改动处标出",
    desc: "不只换字形。软件/軟體、网络/網路、鼠标/滑鼠——台港用词习惯一并处理，改动处逐字标出便于校对。",
    url: "https://icgma.github.io/s2t/",
    repo: "https://github.com/icgma/s2t",
    external: true,
    status: "live",
    categories: ["text"],
    scenarios: ["cross-strait", "foreign-desk"],
    tags: ["简体", "繁体", "台湾正体", "香港字形", "OpenCC", "直角引号"],
    keywords: ["简繁", "繁简", "转换", "台湾", "香港", "港台", "用词", "校对", "发稿", "简转繁", "繁转简"],
    icon: '<path fill="currentColor" d="M4 4h7v2.5H8.6V14H6.4V6.5H4V4Zm8.5 6H20v2h-2.6v5.5h-2.2V12H12.5v-2Z"/><path fill="currentColor" d="M12.8 4h1.9l2.8 4.8h-2.1l-.6-1.2h-2.2l-.6 1.2H10L12.8 4Z" opacity=".55"/>',
  },
  {
    id: "textstats",
    name: "textstats",
    title: "稿件统计",
    tagline: "按汉字计字数，估口播时长，挑出长句",
    desc: "中文按汉字算而不是按空格分词。给出播报时长、阅读时长，并把超过 50 字的长句逐条列出来。",
    url: "https://icgma.github.io/textstats/",
    repo: "https://github.com/icgma/textstats",
    external: true,
    status: "live",
    categories: ["measure", "text"],
    scenarios: ["filing", "cross-strait"],
    tags: ["汉字计数", "朗读时长", "长句", "段落"],
    keywords: ["字数", "统计", "计数", "口播", "播报", "配音", "时长", "可读性", "自查", "编辑", "改稿"],
    icon: '<path fill="currentColor" d="M4 19h16v2H4v-2Zm2-5h2v4H6v-4Zm4-5h2v9h-2V9Zm4 3h2v6h-2v-6Zm4-8h2v14h-2V4Z"/>',
  },
  {
    id: "tidy",
    name: "tidy",
    title: "清稿",
    tagline: "清掉零宽字符、全角字母、多余空白",
    desc: "Word、微信、网页拷出来的稿：零宽字符、全角字母数字、行尾空格、中文标点与引号，粘进来改完复制出去。",
    url: "tidy/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["text"],
    scenarios: ["filing"],
    tags: ["清稿", "零宽字符", "全角", "标点", "引号"],
    keywords: ["清稿", "空格", "零宽", "全角", "半角", "标点", "引号", "微信", "Word", "粘贴", "空白"],
    icon: '<path fill="currentColor" d="M4 4h16v2H4V4Zm0 5h16v2H4V9Zm0 5h10v2H4v-2Zm0 5h7v2H4v-2Z"/>',
  },
  {
    id: "diffmark",
    name: "diffmark",
    title: "逐字对照",
    tagline: "两段稿对照，增删改标色",
    desc: "改稿前后、审稿意见、学生作业。中文按字、英文按词，删的划掉、增的加底。",
    url: "diffmark/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["text"],
    scenarios: ["filing"],
    tags: ["对照", "diff", "改稿", "审稿"],
    keywords: ["对照", "比对", "diff", "改稿", "审稿", "作业", "版本", "逐字", "差异"],
    icon: '<path fill="currentColor" d="M5 4h6v2H5V4Zm0 5h14v2H5V9Zm0 5h9v2H5v-2Zm0 5h14v2H5v-2Z" opacity=".45"/><path fill="currentColor" d="M12 4h7v2h-7V4Z"/>',
  },
  {
    id: "timezone",
    name: "timezone",
    title: "时区换算",
    tagline: "外媒发稿时间换成北京时间，含夏令时",
    desc: "路透 14:30 GMT 发的稿，北京时间几点？含夏令时判断，可同时比对多个新闻中心的当地时间。",
    url: "https://icgma.github.io/timezone/",
    repo: "https://github.com/icgma/timezone",
    external: true,
    status: "live",
    categories: ["measure"],
    scenarios: ["foreign-desk"],
    tags: ["时区", "夏令时", "Unix 时间戳", "ISO 8601"],
    keywords: ["时间", "换算", "北京时间", "格林威治", "GMT", "UTC", "外媒", "路透", "时差", "当地时间"],
    icon: '<path fill="currentColor" d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm0 2a8 8 0 1 1 0 16 8 8 0 0 1 0-16Zm1 3h-2v6l5 3 1-1.7-4-2.3V7Z"/>',
  },
  {
    id: "imgshrink",
    name: "imgshrink",
    title: "图片压缩",
    tagline: "把原图压到能当邮件附件",
    desc: "相机原图动辄 8MB，邮箱附件上限常是 10MB。本地压缩与格式转换，画布重绘去掉 EXIF，图片不上传。",
    url: "imgshrink/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["media"],
    scenarios: ["send-photo"],
    tags: ["压缩", "WebP", "尺寸缩放", "EXIF"],
    keywords: ["图片", "照片", "供图", "邮件附件", "太大", "瘦身", "jpg", "png", "webp", "分辨率"],
    icon: '<path fill="currentColor" d="M21 5H3a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h18a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1Zm-1 2v7.6l-3.3-3.3-3 3-3.2-3.2L4 17.4V7h16ZM8.5 11a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z"/>',
  },
  {
    id: "pvalue",
    name: "pvalue",
    title: "p 值与效应量",
    tagline: "统计量换成 APA 报告，或反推样本量",
    desc: "输入统计量算 p 值、效应量与置信区间，或反推所需样本量。APA 格式报告，一键复制。精确非中心分布计算，与 G*Power 对基准。",
    url: "pvalue/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["measure"],
    scenarios: ["paper-writing"],
    tags: ["p 值", "效应量", "Cohen's d", "η²", "功效分析", "样本量"],
    keywords: ["p值", "显著", "效应量", "统计", "t检验", "F检验", "卡方", "相关", "功效", "样本量", "APA", "置信区间"],
    icon: '<path fill="currentColor" d="M3 3h2v18H3V3Zm0 16h18v2H3v-2Zm4-4 4-6 3 4 5-8v12H7v-2Z"/>',
  },
  {
    id: "redact",
    name: "redact",
    title: "访谈稿匿名化",
    tagline: "访谈稿脱敏，每一处都能复核撤销",
    desc: "自动识别并脱敏访谈稿中的个人信息，每一处替换可逐项复核撤销，满足伦理审查要求。支持自定义规则与 LLM 辅助识别，导出替换映射表。",
    url: "redact/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["text"],
    scenarios: ["interview"],
    tags: ["脱敏", "匿名化", "伦理审查", "IRB", "访谈", "个人信息"],
    keywords: ["脱敏", "匿名", "隐私", "访谈", "人名", "身份证", "手机号", "邮箱", "伦理", "IRB", "遮盖"],
    icon: '<path fill="currentColor" d="M8 1 2 4v4c0 3.6 2.6 6.8 6 7.8 3.4-1 6-4.2 6-7.8V4L8 1Zm0 2.2L13 5.4v2.6c0 2.8-2 5.3-5 6.2-3-.9-5-3.4-5-6.2V5.4L8 3.2ZM7 7v2h2V7H7Zm0 3v2h2v-2H7Z"/>',
  },
  {
    id: "bibfix",
    name: "bibfix",
    title: "参考文献修复",
    tagline: "修好知网、万方导出的 BibTeX 和 RIS",
    desc: "粘贴从 CNKI、万方、Google Scholar 导出的引文，自动修 DOI 前缀、页码连字符、年份、中文人名、全大写标题。不臆造缺失字段，逐条列改动并提醒缺失字段。",
    url: "bibfix/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["litdata"],
    scenarios: ["paper-writing"],
    tags: ["BibTeX", "RIS", "参考文献", "DOI", "引文", "CNKI"],
    keywords: ["参考文献", "引文", "BibTeX", "RIS", "DOI", "页码", "修复", "格式", "CNKI", "万方", "Zotero", "Overleaf"],
    icon: '<path fill="currentColor" d="M4 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4Zm2 0v12h8V4H6Zm2 2h4v2H8V6Zm0 4h4v2H8v-2Z"/>',
  },
  {
    id: "citecheck",
    name: "citecheck",
    title: "引文格式互转",
    tagline: "APA·Chicago·MLA·GB/T 一键互换",
    desc: "粘贴 BibTeX、RIS 或一条任意格式的引文（每行一条），自动识别并转成其余四种。中文作者名、DOI、页码都处理，解析不了的明说。",
    url: "citecheck/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["litdata"],
    scenarios: ["paper-writing"],
    tags: ["引文", "APA", "GB/T 7714", "MLA", "Chicago", "互转"],
    keywords: ["引文格式", "APA", "MLA", "Chicago", "GB/T 7714", "参考文献", "互转", "引用", "citation", "格式转换"],
    icon: '<path fill="currentColor" d="M4 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4Zm2 0v12h8V4H6Zm2 2h4v2H8V6Zm0 4h4v2H8v-2Z" opacity=".45"/><path fill="currentColor" d="m15.6 12.4 4.4 4.4 4.4-4.4 1.4 1.4-5.8 5.8-5.8-5.8 1.4-1.4Z"/>',
  },
  {
    id: "csvclean",
    name: "csvclean",
    title: "CSV 清洗",
    tagline: "问卷导出的 CSV，先体检再清洗",
    desc: "自动认分隔符和编码（UTF-8/GB18030），把混合分隔符、引号不闭合、空列、重复行、数字列混入文本这些问题列出来。清洗动作全部勾选制，文件不出本机。",
    url: "csvclean/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["litdata"],
    scenarios: ["wash-data"],
    tags: ["CSV", "数据清洗", "编码", "分隔符", "重复行"],
    keywords: ["CSV", "数据清洗", "编码", "GBK", "GB18030", "乱码", "分隔符", "重复行", "空列", "问卷", "SPSS", "Excel"],
    icon: '<path fill="currentColor" d="M4 4h16v2H4V4Zm0 5h10v2H4V9Zm0 5h16v2H4v-2Zm0 5h7v2H4v-2Z" opacity=".45"/><path fill="currentColor" d="m17.2 12.4 1.6 1.6 3-3 1.4 1.4-4.4 4.4-3-3 1.4-1.4Z"/>',
  },
  {
    id: "scipdf",
    name: "scipdf",
    title: "PDF 元数据提取",
    tagline: "拖进论文 PDF，抽出标题、作者、DOI",
    desc: "拖入论文 PDF，在浏览器中提取标题、作者、DOI、摘要与卷期页，生成 BibTeX / CSL-JSON。启发式提取，字段可核对可修改。PDF 不上传。",
    url: "scipdf/",
    repo: "https://github.com/icgma/newsroom-kit",
    status: "live",
    categories: ["litdata"],
    scenarios: ["paper-writing"],
    tags: ["PDF", "元数据", "BibTeX", "DOI", "论文", "pdf.js"],
    keywords: ["PDF", "论文", "元数据", "提取", "标题", "作者", "DOI", "摘要", "BibTeX", "文献", "引用"],
    icon: '<path fill="currentColor" d="M6 2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6l-4-4H6Zm8 1.5L16.5 6H14V3.5ZM8 9h8v1H8V9Zm0 3h8v1H8v-1Zm0 3h5v1H8v-1Z"/>',
  },
];
